package com.bsiag.edu.helloworld.helloworld.shared.person;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.bsiag.edu.helloworld.helloworld.client.person.PersonTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public PersonTablePageData() {
  }

  @Override
  public PersonTableRowData addRow() {
    return (PersonTableRowData) super.addRow();
  }

  @Override
  public PersonTableRowData addRow(int rowState) {
    return (PersonTableRowData) super.addRow(rowState);
  }

  @Override
  public PersonTableRowData createRow() {
    return new PersonTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return PersonTableRowData.class;
  }

  @Override
  public PersonTableRowData[] getRows() {
    return (PersonTableRowData[]) super.getRows();
  }

  @Override
  public PersonTableRowData rowAt(int index) {
    return (PersonTableRowData) super.rowAt(index);
  }

  public void setRows(PersonTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class PersonTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String personId = "personId";
    public static final String name = "name";
    public static final String firstname = "firstname";
    private String m_personId;
    private String m_name;
    private String m_firstname;

    public PersonTableRowData() {
    }

    public String getPersonId() {
      return m_personId;
    }

    public void setPersonId(String personId) {
      m_personId = personId;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String name) {
      m_name = name;
    }

    public String getFirstname() {
      return m_firstname;
    }

    public void setFirstname(String firstname) {
      m_firstname = firstname;
    }
  }
}
