package com.bsiag.edu.helloworld.helloworld.shared.person;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.bsiag.edu.helloworld.helloworld.client.person.PersonForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public PersonFormData() {
  }

  public Birthday getBirthday() {
    return getFieldByClass(Birthday.class);
  }

  public Firstname getFirstname() {
    return getFieldByClass(Firstname.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  /**
   * access method for property PersonId.
   */
  public String getPersonId() {
    return getPersonIdProperty().getValue();
  }

  /**
   * access method for property PersonId.
   */
  public void setPersonId(String personId) {
    getPersonIdProperty().setValue(personId);
  }

  public PersonIdProperty getPersonIdProperty() {
    return getPropertyByClass(PersonIdProperty.class);
  }

  public static class Birthday extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public Birthday() {
    }
  }

  public static class Firstname extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Firstname() {
    }
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }
  }

  public static class PersonIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public PersonIdProperty() {
    }
  }
}
